import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  schema: [
    './server/db/schema/*.ts',
    // Better Auth tables (user/session/account/verification) are generated by
    // @nuxtjs/better-auth into .nuxt (exposed as #auth/schema). Run `nuxt prepare`
    // or `pnpm dev` before `db:generate` so this file exists.
    './.nuxt/better-auth/schema.sqlite.mjs',
  ],
  out: './server/db/migrations',
  dialect: 'sqlite',
  driver: 'd1-http',
  dbCredentials: {
    accountId: process.env.CLOUDFLARE_ACCOUNT_ID!,
    databaseId: process.env.CLOUDFLARE_DATABASE_ID!,
    token: process.env.CLOUDFLARE_D1_TOKEN!,
  },
})
