packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': set this to true or false
  better-sqlite3: true
  esbuild: true
  prisma: set this to true or false
  sharp: true
  unrs-resolver: true
  vue-demi: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
